# Crossplatform pyInstaller builds using GitHub Actions

name: pyinstaller

jobs:
  pyinstaller-build:
    runs-on: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '*'
          #spec: 'src/build.spec'
          #requirements: 'src/requirements.txt'
          upload_exe_with_name: 'webactogram'
          options: --onefile, --name "webactogram", --windowed, 
