# Crossplatform pyInstaller builds using GitHub Actions

name: pyinstaller

on:
  push:
    branches:
      - master # $default-branch only works in Workflows templates, not in Workflows, see https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
  pull_request:
    branches:
      - master

jobs:
  pyinstaller-build:
    runs-on: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '*'
          spec: 'webactogram.spec'
          #requirements: 'src/requirements.txt'
          upload_exe_with_name: 'webactogram'
          options: -F, -c, --hidden-import="pkg_resources.py2_warn", --hidden-import="pkg_resources.py3_warn", src/webactogram/webactogram.py